[build]
  publish = "dist"
  command = "npm run build"

# Force HTTPS and WWW redirects
[[redirects]]
  from = "http://cocukbahcem.com/*"
  to = "https://cocukbahcem.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.cocukbahcem.com/*"
  to = "https://cocukbahcem.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.cocukbahcem.com/*"
  to = "https://cocukbahcem.com/:splat"
  status = 301
  force = true

# Netlify domain redirects
[[redirects]]
  from = "https://cocukbahcem.netlify.app/*"
  to = "https://cocukbahcem.com/:splat"
  status = 301
  force = true

# API routes (if you have any)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback - should be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# SEO and Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    # Enhanced SEO Headers
    X-Robots-Tag = "index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

    # Performance and Caching
    X-DNS-Prefetch-Control = "on"

    # Language and Location
    Content-Language = "tr"

    # Additional SEO signals
    X-UA-Compatible = "IE=edge"

# Sitemap and Robots specific headers
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"
    Cache-Control = "public, max-age=86400"

# Structured data headers
[[headers]]
  for = "/structured-data/*.json"
  [headers.values]
    Content-Type = "application/ld+json"
    Cache-Control = "public, max-age=86400"

# Favicon and manifest headers
[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Content-Type = "image/x-icon"
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "/site.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=86400"

# Headers for better caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = "public, immutable, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    cache-control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    cache-control = "public, max-age=31536000"

[[headers]]
  for = "*.woff2"
  [headers.values]
    cache-control = "public, max-age=31536000"

# Image optimization headers
[[headers]]
  for = "*.jpg"
  [headers.values]
    cache-control = "public, max-age=2592000"

[[headers]]
  for = "*.png"
  [headers.values]
    cache-control = "public, max-age=2592000"

[[headers]]
  for = "*.webp"
  [headers.values]
    cache-control = "public, max-age=2592000"