[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# SEO and Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    # SEO Headers
    X-Robots-Tag = "index, follow"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Performance
    X-DNS-Prefetch-Control = "on"
    
    # Language
    Content-Language = "tr"

# Sitemap and Robots specific headers
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"
    Cache-Control = "public, max-age=86400"

# Structured data headers
[[headers]]
  for = "/structured-data/*.json"
  [headers.values]
    Content-Type = "application/ld+json"
    Cache-Control = "public, max-age=86400"

# Headers for better caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = "public, immutable, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    cache-control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    cache-control = "public, max-age=31536000"

[[headers]]
  for = "*.woff2"
  [headers.values]
    cache-control = "public, max-age=31536000"

# Image optimization headers
[[headers]]
  for = "*.jpg"
  [headers.values]
    cache-control = "public, max-age=2592000"

[[headers]]
  for = "*.png"
  [headers.values]
    cache-control = "public, max-age=2592000"

[[headers]]
  for = "*.webp"
  [headers.values]
    cache-control = "public, max-age=2592000"